<?php

	class TextKey {

		public static function getKeys() {
			//Returns an AA. The keys are text keys, the values says if the text can be multilined.
            return array(
                'booking_and' => false,
                'booking_between' => false,
                'booking_deposit' => false,
                'booking_fee' => false,
                'booking_instruction' => true,
                'booking_num_items' => false,
                'book_email_sent' => true,
                'book_thank_you' => false,
				'you_have_booked' => false,
				'book_confirm' => false,
                'calendar_next_month' => false,
                'calendar_previous_month' => false,
				'please_note' => false,
                'cal_apr' => false,
                'cal_aug' => false,
                'cal_dec' => false,
                'cal_feb' => false,
                'cal_jan' => false,
                'cal_jul' => false,
                'cal_jun' => false,
                'cal_mar' => false,
                'cal_may' => false,
                'cal_nov' => false,
                'cal_oct' => false,
                'cal_sep' => false,
                'cal_short_fri' => false,
                'cal_short_mon' => false,
                'cal_short_sat' => false,
                'cal_short_sun' => false,
                'cal_short_thu' => false,
                'cal_short_tue' => false,
                'cal_short_wed' => false,
                'cart_checkout' => false,
                'cart_items_booked' => false,
                'cart_title' => false,
                'confirm_address' => false,
                'confirm_back_to_booking' => false,
                'confirm_email' => false,
                'confirm_eula' => false,
                'confirm_eula_name' => false,
                'confirm_instructions' => true,
                'confirm_intro' => true,
                'confirm_name' => false,
                'confirm_personnummer' => false,
                'confirm_phone' => false,
                'confirm_sum_deposit' => false,
                'confirm_title' => false,
                'error_no_items_booked' => true,
                'error_no_items_selected' => true,
                'error_num_items_not_booked' => true,
                'item_descr_num' => false,
                'item_descr_there_is' => false,
                'max_lending_time' => false,
                'site_title' => false,
                'logout' => false,
                'email_confirm_intro' => true,
                'email_confirm_end' => true,
                'email_reminder_pickup' => true,
                'email_reminder_return' => true,
                'email_reminder_overdue' => true,
                'email_unbook_instructions' => true,
                'unbook' => false,
                'unbooked' => false,
                'eula_text' => true,
                'booking_choose_period' => false,
                'booking_menu_title' => false,
                'calendar_instruction' => true
            );
        }
    }

?>
